# Generated by Django 6.0.3 on 2026-04-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='type',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='capacity',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('van', 'Van'), ('bus', 'Bus'), ('suv', 'SUV')], default='Van', max_length=20),
            preserve_default=False,
        ),
    ]
