# Generated by Django 6.0.3 on 2026-04-27 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0002_remove_vehicle_type_vehicle_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='location',
        ),
        migrations.AddField(
            model_name='accommodation',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Bookings.destination'),
            preserve_default=False,
        ),
    ]
