# Generated by Django 6.0.3 on 2026-04-27 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0003_remove_accommodation_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='destination',
        ),
        migrations.AddField(
            model_name='accommodation',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Bookings.location'),
            preserve_default=False,
        ),
    ]
